### PR TITLE
Dotty

### PR DESCRIPTION
**Pull request by rossabaker**
Compiles, but the tests are sparse, and I have no faith that the logger names are correct.  We're using the meaty macro out of log4s.

### CODE REVIEW

**Comment by rossabaker** [comment]
Uh, do these builds have a history of hanging?

**Comment by ChristopherDavenport** [comment]
Nope, not generally

**Review by ChristopherDavenport — COMMENTED** [review]
This looks good, just need to fix up the whatever's hanging.

**Comment by rossabaker** [comment]
It's not just Dotty, which is weird.  Not so much else changed.

**Comment by rossabaker** [comment]
If it hangs again, hopefully the dotty-hang branch will expose it.

**Comment by rossabaker** [comment]
It's caught in the mess of `dirtyStuff`, but I don't know why it's broken now.

**Comment by rossabaker** [comment]
So, non-deterministically, getting the MDC variable for the finalizer thread was happening from the finalizer thread.  I gave it a third thread to that we can shift back to as "main", ensuring that the producer is not the consumer on the blocking calls, and it passed on all builds.  I will run again for greater confidence.

**Review by lorandszakacs — APPROVED** [review]
LGTM. Did a quick and dirty verification of the logger names.

Will add some tests for it in the near future.

**Comment by rossabaker** [comment]
Thanks, @lorandszakacs! There's a nice [test suite in log4s](https://github.com/Log4s/log4s/blob/master/core/shared/src/test/scala/org/log4s/GetLoggerSpec.scala) that might be something we could adapt to get some rigor on the logger names.

**Comment by rossabaker** [comment]
Thanks, @lorandszakacs! There's a nice [test suite in log4s](https://github.com/Log4s/log4s/blob/master/core/shared/src/test/scala/org/log4s/GetLoggerSpec.scala) that might be something we could adapt to get some rigor on the logger names.

**Comment by rossabaker** [comment]
Thanks, @lorandszakacs! There's a nice [test suite in log4s](https://github.com/Log4s/log4s/blob/master/core/shared/src/test/scala/org/log4s/GetLoggerSpec.scala) that might be something we could adapt to get some rigor on the logger names.

**Review by ChristopherDavenport — APPROVED** [review]

**Pull request merged**
