### PR TITLE
Add `NoOpFactory` implicit in package object

### PR DESCRIPTION
**Pull request by armanbilge**
This is the no-op equivalent of:
https://github.com/typelevel/log4cats/blob/4f02ef39fbee3568c9eaa52fee42904247988c62/slf4j/src/main/scala/org/typelevel/log4cats/slf4j/package.scala#L23

### CODE REVIEW

**Review by danicheg — COMMENTED** [review]
We intentionally didn't add an implicit method when adding `NoOpFactory`, [see](https://github.com/typelevel/log4cats/pull/667#pullrequestreview-1023423720). I personally beware of this kind of thing since it accidentally may hurt someone in $PROD. Especially considering that some $IDE can suggest import when implicit value is required. But I can be overthinking about this. So, if the majority will be happy with this implicit method, I will be happy too.

**Comment by armanbilge** [comment]
> Especially considering that some $IDE can suggest import when implicit value is required.

If this is so dangerous then I argue that `LoggerFactory` actually should not be an implicit at all. Since there can be multiple implementations, doesn't this go against our philosophy anyway?

**Comment by danicheg** [comment]
> Since there can be multiple implementations, doesn't this go against our philosophy anyway?

Sorry, I don't quite follow your idea. I mean that if this method is just for tests, then it shouldn't be too hard to create an implicit instance on the user side. Or, probably, we can add this method straightforwardly to the `testing` module. Then it'd be a little safer from accidental bugs. But again, all of this could be just my imagination.

**Comment by armanbilge** [comment]
Ok, fair enough. My motivation is that currently there is no `LoggerFactory` for Scala.js. But maybe better to solve that problem directly.
- https://github.com/typelevel/log4cats/issues/680

We will have a bigger problem for Scala Native, because there is no standard logging framework there.

**Comment by armanbilge** [comment]
> Or, probably, we can add this method straightforwardly to the `testing` module.

To be fair, it's already isolated to the no-op module. If no-op was part of core that would be a bigger problem, but seems just as hard to add a no-op dependency as it is to add testing dependency :)

**Comment by danicheg** [comment]
> If no-op was part of core that would be a bigger problem, but seems just as hard to add a no-op dependency as it is to add testing dependency :)

Yeah, true. Probably initial authors considering this fine. So I'm speaking just as a random guy from the community 🙇🏻‍♂️

**Comment by lorandszakacs** [comment]
LGTM. The implicit `LoggerFactory` for a `Sync` in `slf4j ` module is way more dangerous :D and if we live with that we can at least be consistent about it.

**Review by lorandszakacs — APPROVED** [review]

**Comment by lorandszakacs** [comment]
I also lean towards deprecating the implicit creation of the factory in slf4j, in which case this indeed should be closed 😄

But I do not agree with encouraging people to not pass `LoggerFactory` implicitly, only with its automagic implicit creation. At the end of the day how many users will have more than one instance of a LoggerFactory in their codebase? And if they do, there always various ways of newtype-ing, or subclassing it, etc. to solve the problem. For large codebases with literally hundreds of classes 90% of which do logging users will probably pass these around implicitly.

**Comment by bplommer** [comment]
Why not provide this as a convenience but in an `implicits` namespace, like we do with (for example) the cats-effect global runtime? That way it's not just "floating around out there" but it's available in a convenient form when needed.

**Comment by lorandszakacs** [comment]
@armanbilge Shall we close this PR, and see if @bplommer's idea lands either in #683 or a follow-up?

**Comment by armanbilge** [comment]
Ah yes, I think we're all agreed we don't want to do this.

**Pull request closed without merging**
