### PR TITLE
Add favicon to the microsite

### PR DESCRIPTION
**Pull request by danicheg**

### CODE REVIEW

**Comment by armanbilge** [comment]
Since this is so important to you I can merge https://github.com/typelevel/sbt-typelevel/pull/133 instead of hacking all the builds :) I really wish we could solve https://github.com/typelevel/sbt-typelevel/issues/144.

**Comment by danicheg** [comment]
@armanbilge I think that `sbt-typelevel` should fix that in its own manner, considering the plans about having a dedicated template. Just because it will take some time, I think we may add this temporary workaround for some projects (I'll be the first who will remove it after fixing it in the upstream 😄).

**Comment by armanbilge** [comment]
Ok thanks :) I'm very sorry I didn't prioritize this favicon issue 😬  btw apologies for interfering, I'm just trying really hard to keep all the builds unified as much as possible, I was also complaining in https://github.com/typelevel/discipline/pull/318 😉

**Comment by danicheg** [comment]
This will wait for https://github.com/typelevel/sbt-typelevel/pull/180

**Pull request closed without merging**
